feat : update ports

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -29,15 +29,12 @@ jobs:
           docker compose pull
           docker compose up -d
 
-      - name: Check health for all services
+      - name: Vérification des routes Traefik
         run: |
-          echo "⏳ Attente du démarrage complet des conteneurs..."
-          sleep 30  # tu peux ajuster selon la rapidité de build
-
-          echo "🔎 Vérification des APIs exposées via Traefik (port 80)..."
-          curl -f http://localhost:80/clients/health    || (echo "::error ::Clients API failed" && exit 1)
-          # curl -f http://localhost/produits/health   || (echo "::error ::Produits API failed" && exit 1)
-          # curl -f http://localhost/commandes/health  || (echo "::error ::Commandes API failed" && exit 1)
+          sleep 30
+          curl -f http://localhost/clients/health || (echo "Clients API failed" && exit 1)
+          curl -f http://localhost/produits/health || (echo "Produits API failed" && exit 1)
+          curl -f http://localhost/commandes/health || (echo "Commandes API failed" && exit 1)
 
           echo "🔎 Vérification des services techniques..."
           curl -f http://localhost:15672              || (echo "::error ::RabbitMQ UI not available" && exit 1)
