feat: supp comment curl

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -31,9 +31,9 @@ jobs:
 
       - name: Vérification des routes Traefik
         run: |
-          # curl -f http://localhost/clients/health || (echo "Clients API failed" && exit 1)
-          # curl -f http://localhost/produits/health || (echo "Produits API failed" && exit 1)
-          # curl -f http://localhost/commandes/health || (echo "Commandes API failed" && exit 1)
+          curl -f http://localhost/clients/health || (echo "Clients API failed" && exit 1)
+          curl -f http://localhost/produits/health || (echo "Produits API failed" && exit 1)
+          curl -f http://localhost/commandes/health || (echo "Commandes API failed" && exit 1)
       - name: Ajout des entrées dans /etc/hosts pour les domaines locaux
         run: |
           echo "127.0.0.1 rabbitmq.localhost prometheus.localhost grafana.localhost kibana.localhost traefik.localhost" | sudo tee -a /etc/hosts
